### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by YujiSoftware** [GOROman/GoodbyeGeocitiesJP#1]
Firefox 版のリリースを希望します。

Firefox も WebExtensions に対応しているので、addons.mozilla.org にアップロードするだけで動くと思います。
https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/Distribution/Submitting_an_add-on

**Comment by GOROman** [comment]
@KusaReMKN さんがFirefox版を作ってくれました。
https://addons.mozilla.org/ja/firefox/addon/goodbye-geocities-jp-4-firefox/
